name: Build & Publish Docker image

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version number
        required: true

jobs:
  publish:
    name: Build & Publish to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build the Docker image
        run: docker build -t my-image:latest .

      - name: Push the Docker image
        run: docker push my-image:latest
