name: Build & Publish Docker Image to Docker Hub

on:
  release:
    types: [created]  # Trigger when a new release is created
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish:
    name: Build & Publish to DockerHub
    runs-on: ubuntu-22.04


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version and app name
        id: vars
        run: |
          version="${{ github.event.release.tag_name || github.event.inputs.version || 'latest' }}"
          major_version=$(echo "$version" | cut -d '.' -f 1)
          echo "app_name=convert-commander" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "major_version=$major_version" >> $GITHUB_OUTPUT

      - name: Display version info
        run: |
          echo "App Name: ${{ steps.vars.outputs.app_name }}"
          echo "Version: ${{ steps.vars.outputs.version }}"
          echo "Major Version: ${{ steps.vars.outputs.major_version }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/convert-commander:latest
            ${{ secrets.DOCKER_USERNAME }}/convert-commander:${{ steps.vars.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/convert-commander:${{ steps.vars.outputs.major_version }}
